version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: password
      JWT_SECRET_KEY: "5c2fea6305c8c209714e73b265958703e65c4b40dec4c388dddac06f3f791ec7"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reaction_db
      LANG: en_US.utf8
      TZ: 'Asia/Seoul'
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

